travis:
  secure:
    BINSTAR_TOKEN: SUKYK+G3WOFx9wyCJlKRZtWhEEPImxZ39OPFYTzqARAThF8D3KyudsAh3xXTCESKVtgnMxldf6HyAOKW8gOt/F+YXnIZhEQTGZBqR0UVSDbZ0Jr772jji+MScKop4mOqhgGrkIdKi5vB0/yXlI1+m4RfA1krH8rZDawoCX1HSiR4cDg2NYNp1qsMsu0DnPqctQ/mCWbgtaPn+OJeRfMDPahZ9PpDrmkJ5SA8RSMuJb+fvIiEJDNjTykdq50OHIOSVq96TKLv/a9kOqbpkegCJP2tAQxdPfp+xogWYlRlks+dRpbkEE9pdOljYGP0sP7PKE2/PetIlI7SSWVRcB6Cqa3nm4C0zHwjByrKIimWocifP4GXqFExBDFT5hm+yIBTEjryWD597tJq0D+EsMiPlAsT+DkMoK0+pflEBC8lpbZHI0A9lSN0GyU5zEDRYOPAQ/XnpWa+mfFUr15AAon9Ze8OniCGQ8J1YujaEmImUraGe/pa3OCuJ+jxqJFcJBlZXhI2GHrPzP31MnvgwXf5cjMbq8lmfmIc9SNEX41BmZx+hP9CmLNjePu1GEO2phvtk2lTK3xBnksu84xzZiBVQW8NG8q4RodNKlb81Xu8HQrNq8dxuM0E+ea7WAc5nk0x5B/QEL1+rne7GI/klgvwThAN1kTtqpAcaCZLGnnEOBs=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
