travis:
  secure:
    BINSTAR_TOKEN: RrmByLHxi3YhV2vtwG0vDh23239zQW8mLhfhl4YNVGcB55qX+8uIJseOrA9z0n7tSpbCypyQ3KqTTC5lMH1zQOdVsGEqZyXBWP/pCQzoguB2bQQ4oGYKyUrl+nicuozSMDpzNoCmiy6dsBDbBM8wbESTLSgo/dOepCway4Ju4iNLjS9bUnnIQ4HRpdpQASOpNua5p23aqEYzw4qbnP+qbzqVHoV3nvcVB1KfLzaFBSJiiXnE4YUdxMIE+Rxu6EGrvKVmng5/GkSaa4+Wz935Fs3nZKW/yVBUWvOqUeYiBGuwJljy5jCyaExvzEyvmv1sNVNZQI0kDDQFTk/9AzGdY+G+QUTk48vF8HdriUaResP33X3hedghWd9MlLIDeMgx7Yf7hk8kgdspdIyWpptuS8qYzr8ZI+Waa6rgjtd6iKZf2hCyuiRO95QkmOqZFJqr8JdXjlc9sw6fZ+6/3r2B/EdXufK1umAuaYoh0XEe8jE70GnmHwSXTv01qw+AAS+ehignKBq8V7f3cpx40oou1SBSNMUm+OhebqI8pI3hBfpiuViahzZL00XWiZ9nc9TpdIxWjwqWTqR52F5seuQqemZINh2RgnyNjTPWPmDstuWu3B2w3FyLRMARk31omziTErTdqEZ2FdwLg5mnPFxHZhgaNyle9tlPSumbPnZz3lY=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
